version: '3.8'

networks:
  ecom-network:
    driver: bridge

services:
  config-service:
    image: olivierkkoc/ecom-config-service:latest
    container_name: config-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/OlivierKouokam/ecom-config-repo.git
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  gateway-service:
    image: olivierkkoc/ecom-gateway-service:latest
    container_name: gateway-service
    ports:
      - "9999:9999"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888/
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_ENABLED=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - SPRING_CLOUD_GATEWAY_ROUTES_0_ID=customer-route
      - SPRING_CLOUD_GATEWAY_ROUTES_0_URI=http://customer-service:8081
      - SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0=Path=/customers/**
      - SPRING_CLOUD_GATEWAY_ROUTES_1_ID=inventory-route
      - SPRING_CLOUD_GATEWAY_ROUTES_1_URI=http://inventory-service:8082
      - SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0=Path=/products/**
    networks:
      - ecom-network
    depends_on:
      config-service:
        condition: service_healthy

  customer-service:
    image: olivierkkoc/ecom-customer-service:latest
    container_name: customer-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - ecom-network
    depends_on:
      config-service:
        condition: service_healthy

  inventory-service:
    image: olivierkkoc/ecom-inventory-service:latest
    container_name: inventory-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - ecom-network
    depends_on:
      config-service:
        condition: service_healthy