server.port=8888
spring.application.name=config-service

# Repo local (option recommandée en dev/VM)
spring.cloud.config.server.git.uri=file://${HOME}/TRAINING/ecom-config-repo
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

# Alternative : repo GitHub distant
# spring.cloud.config.server.git.uri=https://github.com/OlivierKouokam/ecom-config-repo.git

management.endpoints.web.exposure.include=*