apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
data:
  application.properties: |
    spring.datasource.url=jdbc:h2:mem:customers-db
    customers.default.location=Spain
    customers.default.discount=0.03