apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  application.yml: |
    spring:
      cloud:
        gateway:
          routes:
            - id: customer-route
              uri: http://customer-service:8081
              predicates:
                - Path=/customers/**
            - id: inventory-route
              uri: http://inventory-service:8082
              predicates:
                - Path=/products/**